# Generated by Django 6.0.5 on 2026-06-02 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
