# Generated by Django 6.0.5 on 2026-06-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_rename_is_activate_category_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='quentity',
            new_name='quantity',
        ),
    ]
